name: Build Dylib
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache Theos
        uses: actions/cache@v4
        with:
          path: ~/theos
          key: theos-${{ runner.os }}
      
      - name: Setup Theos
        uses: Randomblock1/theos-action@main
      
      - name: Build package
        run: make package FINALPACKAGE=1
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UniversalVIP-Dylib
          path: .theos/obj/**/*.dylib
